### Chloe Quinto    
CPE 695 WS   
HW 4   
I pledge my honor that I have abided by the Stevens Honor System - Chloe Quinto    

In [118]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from tabulate import tabulate

In [119]:
titanic = pd.read_csv('./data/Titanic.csv')
titanic 

Unnamed: 0 pclass  survived                             name     sex  \
0              1    1st         1    Allen, Miss. Elisabeth Walton  female   
1              2    1st         1   Allison, Master. Hudson Trevor    male   
2              3    1st         0     Allison, Miss. Helen Loraine  female   
3              4    1st         0  Allison, Mr. Hudson Joshua Crei    male   
4              5    1st         0  Allison, Mrs. Hudson J C (Bessi  female   
...          ...    ...       ...                              ...     ...   
1304        1305    3rd         0             Zabour, Miss. Hileni  female   
1305        1306    3rd         0            Zabour, Miss. Thamine  female   
1306        1307    3rd         0        Zakarian, Mr. Mapriededer    male   
1307        1308    3rd         0              Zakarian, Mr. Ortin    male   
1308        1309    3rd         0               Zimmerman, Mr. Leo    male   

          age  sibsp  parch  ticket        fare    cabin     embarked boat  \
0     29.0000      0      0   24160  211.337494       B5  Southampton    2   
1      0.9167      1      2  113781  151.550003  C22 C26  Southampton   11   
2      2.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   
3     30.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   
4     25.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   
...       ...    ...    ...     ...         ...      ...          ...  ...   
1304  14.5000      1      0    2665   14.454200      NaN    Cherbourg  NaN   
1305      NaN      1      0    2665   14.454200      NaN    Cherbourg  NaN   
1306  26.5000      0      0    2656    7.225000      NaN    Cherbourg  NaN   
1307  27.0000      0      0    2670    7.225000      NaN    Cherbourg  NaN   
1308  29.0000      0      0  315082    7.875000      NaN  Southampton  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 15 columns]

## Step 1: 

Use our "titanic" dataset in homework #3 and split the data the same way you did in homework #3 as training and testing sets 

In [120]:
titanic.dropna(how="all", inplace=True) #drop all the rows where all elements are missing 

In [121]:
feature_columns = ["pclass", "sex", "age", "sibsp"]

titanic["survived"] = titanic["survived"].astype(int)
y = titanic["survived"]
x = titanic[feature_columns].apply(LabelEncoder().fit_transform)

In [122]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size = 0.3, random_state = 1)

In [123]:
print("xtrain shape: ", xtrain.shape)
print("xtest shape: ", xtest.shape)
print("\n")
print("ytrain shape", ytrain.shape)
print("ytest shape", ytest.shape)

xtrain shape:  (916, 4)
xtest shape:  (393, 4)


ytrain shape (916,)
ytest shape (393,)


In [124]:
xtest.describe().transpose()

count       mean        std  min   25%   50%   75%    max
pclass  393.0   1.264631   0.854876  0.0   0.0   2.0   2.0    2.0
sex     393.0   0.628499   0.483822  0.0   0.0   1.0   1.0    1.0
age     393.0  83.503817  88.186870  2.0  32.0  48.0  76.0  360.0
sibsp   393.0   0.473282   0.914689  0.0   0.0   0.0   1.0    5.0

## Step 2 

Fit a neural network using independent variables 'pclass + sex + age + sibsp' and independent variable 'survived'. Omit all NA examples. Use ***2 hidden layers*** and set the activation functions for both the hidden and output layer to be the sigmoid function. Set the "solver" parameter as either SGD (stochastic gradient descent) or Adam (similar to SGD but optimized performance with mini batches). You can adjust parameter "alpha" for regularlization (to control overfitting) and other parameters such as "learning rate" and "momentum" as needed 

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes = (10, 10), 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 200, 
                    verbose=True) 

In [ ]:
mlp.fit(xtrain, ytrain)

Return the mean accuracy on the given test data and labels 

In [ ]:
score100 = mlp.score(xtrain, ytrain)
print(score100)

In [ ]:
predictions = mlp.predict(xtest)

In [ ]:
print(confusion_matrix(ytest, predictions))

In [ ]:
print(classification_report(ytest, predictions))

## Step 3: 

Check the performance of the model: in sample and out-of-sample accuracy. Please try two different network structures (i.e. number of neurons at each hideen layer) and show their respective accuracy. 

In [ ]:
# In samples percent survivors/fatalities correctly predicted (on training set)
inSample_y = mlp.predict(xtrain)
inSampleSurvivors = 1 - sum(inSample_y[ytrain == 1] ^ ytrain[ytrain == 1]) / len(ytrain[ytrain == 1])
inSampleFatalities = 1 - sum(inSample_y[ytrain == 0] ^ ytrain[ytrain == 0]) / len(ytrain[ytrain == 0])

# out-of-samples percent survivors/fatalities correctly predicted (on training set)
outSample_y = mlp.predict(xtest)
outSampleSurvivors = 1 - sum(inSample_y[ytrain == 1] ^ ytrain[ytrain == 1]) / len(ytrain[ytrain == 1])
outSampleFatalities = 1 - sum(inSample_y[ytrain == 0] ^ ytrain[ytrain == 0]) / len(ytrain[ytrain == 0])

print("In sample percent survivors correctly predicted: {:.2f}%".format(inSampleSurvivors*100))
print("In sample percent fatalaties correctly predicted: {:.2f}%".format(inSampleFatalities*100))
print("Out sample percent survivors correctly predicted: {:.2f}%".format(outSampleSurvivors*100))
print("Out sample percent survivors correctly predicted: {:.2f}%".format(outSampleFatalities*100))

---

#### 3.1 Changing number of neurons in the hidden layer 

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes = (100, 100), # 4 features + 1 label column 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 200, 
                    verbose=True) 

In [ ]:
mlp.fit(xtrain, ytrain)

In [ ]:
score5 = mlp.score(xtrain, ytrain)
print(score5)

In [ ]:
predictions = mlp.predict(xtest)

In [ ]:
print(confusion_matrix(ytest, predictions))

In [ ]:
print(classification_report(ytest, predictions))

In [ ]:
# In samples percent survivors/fatalities correctly predicted (on training set)
inSample_y = mlp.predict(xtrain)
inSampleSurvivors = 1 - sum(inSample_y[ytrain == 1] ^ ytrain[ytrain == 1]) / len(ytrain[ytrain == 1])
inSampleFatalities = 1 - sum(inSample_y[ytrain == 0] ^ ytrain[ytrain == 0]) / len(ytrain[ytrain == 0])

# out-of-samples percent survivors/fatalities correctly predicted (on training set)
outSample_y = mlp.predict(xtest)
outSampleSurvivors = 1 - sum(inSample_y[ytrain == 1] ^ ytrain[ytrain == 1]) / len(ytrain[ytrain == 1])
outSampleFatalities = 1 - sum(inSample_y[ytrain == 0] ^ ytrain[ytrain == 0]) / len(ytrain[ytrain == 0])

print("In sample percent survivors correctly predicted: {:.2f}%".format(inSampleSurvivors*100))
print("In sample percent fatalaties correctly predicted: {:.2f}%".format(inSampleFatalities*100))
print("Out sample percent survivors correctly predicted: {:.2f}%".format(outSampleSurvivors*100))
print("Out sample percent survivors correctly predicted: {:.2f}%".format(outSampleFatalities*100))

In [ ]:
print("A Multi-layer Perceptron with two hidden layers of 10 neurons each had an accuracy score\n of on the given test data and labels:",  score100)
print("A Multi-layer Perceptron with two hidden layers of 100 neurons each had an accuracy score\n of on the given test data and labels:",  score5)

## Step 4

Compare the in-sample and out-of-sample accuracy (as defined in step 3) with the pruned decision tree obtained in homework #3 (You can either use a table of a figure to compare the accuracy of the two learning algorithms

In [ ]:
print(tabulate([
                ["In-Sample Survivors",  inSampleSurvivors*100 , 96.61835748792271], 
                ["In-Sample Fatalities",inSampleFatalities*100, 79.12552891396332], 
                ["Out-of-Sample Survivors", outSampleSurvivors*100, 85.22727272727273], 
                ["Out-of-Sample Fatalitiles", outSampleFatalities*100,74.75409836065575]], 
            headers=['Accuracy','MLP: Value', 'Pruned Tree: Value']))

Our results show that a pruned tree performed with a higher accuracy for determining in-sample survivors as well as out-of-sample survivors. This may be due to the fact that with MLP, we have attributes that we have to fine tune ourselves. 

## Bonus

Implement Backpropagation

In [162]:
mlp = MLPClassifier(hidden_layer_sizes = (100, 100), # 4 features + 1 label column 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 200, 
                    verbose=True) 

In [163]:
mlp.fit(xtrain, ytrain)

Iteration 1, loss = 0.66906598
Iteration 2, loss = 0.66637702
Iteration 3, loss = 0.66019695
Iteration 4, loss = 0.65842603
Iteration 5, loss = 0.65660210
Iteration 6, loss = 0.65435438
Iteration 7, loss = 0.65362050
Iteration 8, loss = 0.65206206
Iteration 9, loss = 0.65053294
Iteration 10, loss = 0.64995331
Iteration 11, loss = 0.64881914
Iteration 12, loss = 0.64719832
Iteration 13, loss = 0.64597651
Iteration 14, loss = 0.64443833
Iteration 15, loss = 0.64389677
Iteration 16, loss = 0.64149881
Iteration 17, loss = 0.63938615
Iteration 18, loss = 0.63734622
Iteration 19, loss = 0.63503574
Iteration 20, loss = 0.63295656
Iteration 21, loss = 0.62977600
Iteration 22, loss = 0.62687413
Iteration 23, loss = 0.62347995
Iteration 24, loss = 0.61977170
Iteration 25, loss = 0.61579207
Iteration 26, loss = 0.61055881
Iteration 27, loss = 0.60565992
Iteration 28, loss = 0.60041756
Iteration 29, loss = 0.59648181
Iteration 30, loss = 0.58667588
Iteration 31, loss = 0.58358281
Iteration 32, los

MLPClassifier(activation='logistic', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 100), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.1, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [164]:
mlp.coefs_

[array([[-1.86681710e-01,  1.32301717e-01, -2.40684272e-01,
         -2.88862094e-01,  6.28139622e-02,  3.16426413e-01,
          7.90602892e-02,  5.53526238e-02, -9.07443087e-02,
          3.16327961e-01, -1.16409197e-01, -2.19210587e-01,
          2.03248311e-01, -1.34997255e-01, -3.79424068e-02,
         -1.76625994e-01,  5.20144775e-02,  7.02207582e-03,
         -2.12426998e-01,  3.03758452e-03, -2.65639394e-01,
         -4.68742143e-02,  1.74215883e-01, -2.37973031e-01,
         -7.55690275e-02,  9.90391018e-02, -1.27531987e-01,
          2.62766934e-01, -1.03962245e-01,  1.66947787e-01,
          1.46395632e-01,  1.54819846e-01,  1.05981384e-01,
         -1.75178918e-01, -3.50572457e-01,  3.27902992e-01,
         -7.53402383e-02,  1.80079289e-01, -1.69729268e-01,
          3.13240248e-01,  9.10660281e-02,  3.41383245e-01,
         -2.15921081e-01,  2.81873302e-01, -2.65537589e-01,
          6.14934410e-02, -6.84951759e-04, -3.24186192e-01,
          2.01453985e-01, -3.51620951e-0

Instead of calling MLPClassifier(), let's intuitively build what a neural network looks like 

In [ ]:
# class NeuralNetwork: 
#     def __init__(self): 
#         np.random.seed(10)
import numpy as np

xtrain = np.array(xtrain)
ytrain = np.array(ytrain)

ytrain

I assume bias is 0 

In [165]:
class NeuralNetwork:
    def __init__(self):
#         np.random.seed(10) 
        self.wij = np.random.uniform(-0.1, 0.1)
        self.wjk  = np.random.uniform(-0.1,0.1) 
        self.wkl = np.random.uniform(-0.1, 0l)

    def sigmoid(self, x, w):
        z = np.dot(x, w)
        return 1/(1 + np.exp(-z))
    
    def sigmoid_derivative(self, x, w):
        return self.sigmoid(x, w) * (1 - self.sigmoid(x, w))
    
    def gradient_descent(self, x, y, iterations):
        for i in range(iterations):
            Xi = x
            Xj = self.sigmoid(Xi, self.wij)
            yhat = self.sigmoid(Xj, self.wjk)

            g_wjk = np.dot(Xj.T, (y - yhat) * self.sigmoid_derivative(Xj, self.wjk))

            g_wij = np.dot(Xi.T, np.dot((y - yhat) * self.sigmoid_derivative(Xj, self.wjk), np.transpose(self.wjk)) * self.sigmoid_derivative(Xi, self.wij))
            self.wij += g_wij
            self.wjk += g_wjk
        print('Predicted Weights')
        print(yhat) 
        return yhat

In [168]:
import numpy as np
import math
nn = NeuralNetwork()
# x = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
# y = np.array([[0, 1, 1, 0]]).T
x = np.array(xtrain)
y = np.array([ytrain]).T
val = nn.gradient_descent(x,y,4000)
print(val)

Predicted Weights
[[9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 ...
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]]
[[9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 ...
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]
 [9.76861683e-19 1.02275964e-18 7.60593440e-20 1.03409631e-18]]
